language: cpp
sudo: false
os: linux
compiler: gcc

notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0


matrix:
  include:
    # GCC 5
    - env: COMPILER=g++-5
      compiler: gcc
      addons: &gcc5
        apt:
          packages: ["g++-5", "valgrind"]
          sources: *apt_sources

    #~ # GCC 6
    #~ - env: COMPILER=g++-6
      #~ compiler: gcc
      #~ addons: &gcc6
        #~ apt:
          #~ packages: ["g++-6", "valgrind"]
          #~ sources: *apt_sources

    #~ # GCC 7
    #~ - env: COMPILER=g++-7
      #~ compiler: gcc
      #~ addons: &gcc7
        #~ apt:
          #~ packages: ["g++-7", "valgrind"]
          #~ sources: *apt_sources

    #~ # Clang 4.0
    #~ - env: COMPILER=clang++-4.0 ADDITIONAL_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined"
      #~ addons: &clang40
        #~ apt:
          #~ packages: ["clang-4.0", "valgrind", "g++-6"]
          #~ sources: *apt_sources

    #~ # Clang 5.0
    #~ - env: COMPILER=clang++-5.0 ADDITIONAL_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined"
      #~ addons: &clang50
        #~ apt:
          #~ packages: ["clang-5.0", "valgrind", "g++-6"]
          #~ sources: *apt_sources

before_script:
  - ${COMPILER} --version
  - cmake --version

script:
  # sanitize options
  - export ASAN_OPTIONS=allow_addr2line=true:check_initialization_order=true:strict_init_order=true:strict_string_checks=true:detect_odr_violation=2:detect_stack_use_after_return=true:verbosity=0
  # examples
  - cd example
  - mkdir -p debug_build
  - cd debug_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="${ADDITIONAL_CXX_FLAGS}"
  - make -j2
  - ./basic
  - cd ..
  - mkdir -p release_build
  - cd release_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${ADDITIONAL_CXX_FLAGS}"
  - make -j2
  - ./basic
  - cd ..
  # tests
  - cd test
  - mkdir -p debug_build
  - cd debug_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="${ADDITIONAL_CXX_FLAGS}"
  - make -j2
  - ctest --output-on-failure
  - cd ..
  - mkdir -p release_build
  - cd release_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${ADDITIONAL_CXX_FLAGS}"
  - make -j2
  - ctest --output-on_failure

